# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

StockExchange.create(name: "London Stock Exchange", country:"England",address: "10 Paternoster Sq., London EC4M 7LS ", history: " The Royal Exchange had been founded by English financier Thomas Gresham and Sir Richard Clough on the model of the Antwerp Bourse. It was opened by Elizabeth I of England in 1571.[4][5]      
    During the 17th century, stockbrokers were not allowed in the Royal Exchange due to their rude manners. They had to operate from other establishments in the vicinity, notably Jonathan's Coffee-House. At that coffee house, a broker named John Castaing started listing the prices of a few commodities, such as salt, coal, and paper, and exchange rates in 1698. Originally, this was not a daily list and was only published a few days of the week.[6]
    This list and activity was later moved to Garraway's coffee house. Public auctions during this period were conducted for the duration that a length of tallow candle could burn; these were known as 'by inch of candle' auctions. As stocks grew, with new companies joining to raise capital, the royal court also raised some monies. These are the earliest evidence of organised trading in marketable securities in London.
    ") 

StockExchange.create(name: "Nikkei 225,日経平均株価 ", country:"Japan",address: "1-3-7 Otemachi Chiyoda-ku Tokyo, 100-8066 Japan", history:"The Nikkei 225 (日経平均株価, Nikkei heikin kabuka), more commonly called the Nikkei, the Nikkei index, or the Nikkei Stock Average[1][2] (/ˈnɪkeɪ, ˈniː-, nɪˈkeɪ/), is a stock market index for the Tokyo Stock Exchange (TSE). It has been calculated daily by the Nihon Keizai Shimbun (The Nikkei) newspaper since 1950. It is a price-weighted index, operating in the Japanese Yen (JP¥), and its components are reviewed once a year. The Nikkei measures the performance of 225 large, publicly owned companies in Japan from a wide array of industry sectors.[3]
The Nikkei 225 began to be calculated on 7 September 1950; 69 years ago, retroactively calculated back to 16 May 1949. Since January 2010, the index is updated every 15 seconds during trading sessions.")
 StockExchange.create(name:"Nasdaq", country:"USA", address: "One Liberty Plaza 165 Broadway Manhattan, New York City, New York, U.S.", history:" The Nasdaq Stock Market, also known as Nasdaq or NASDAQ, is an American stock exchange located at One Liberty Plaza in New York City. It is ranked second on the list of stock exchanges by market capitalization of shares traded, behind only the New York Stock Exchange. The exchange platform is owned by Nasdaq, Inc.,[3] which also owns the Nasdaq Nordic stock market network and several U.S. stock and options exchanges.")
 StockExchange.create(name:"New York Stock Exchange", country:"USA", address:"11 Wall St, New York, NY 10005, United States", history:" The earliest recorded organization of securities trading in New York among brokers directly dealing with each other can be traced to the Buttonwood Agreement. Previously, securities exchange had been intermediated by the auctioneers, who also conducted more mundane auctions of commodities such as wheat and tobacco.[11] On May 17, 1792, twenty four brokers signed the Buttonwood Agreement, which set a floor commission rate charged to clients and bound the signers to give preference to the other signers in securities sales. The earliest securities traded were mostly governmental securities such as War Bonds from the Revolutionary War and First Bank of the United States stock,[11] although Bank of New York stock was a non-governmental security traded in the early days.[12] The Bank of North America, along with the First Bank of the United States and the Bank of New York, were the first shares traded on the New York Stock Exchange.[13]")


Company.create(name:"Apple", password:"apple", address:"Cupertino, California", description:"Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Tech technology companies, alongside Amazon, Google, Microsoft and Facebook.", industry:"Tech")
Company.create(name:"Goldman Sachs", password:"goldman", address:"200 West Street, New York", description:"The Goldman Sachs Group, Inc., (/sæks/) is an American multinational investment bank and financial services company headquartered in New York City. It offers services in investment management, securities, asset management, prime brokerage, and securities underwriting. It also provides investment banking to institutional investors.", industry:"Banking")

Company.create(name:"Barclays", password:"barclays", address:"Canary Wharf, London", description:"Barclays plc (/ˈbɑːrkliz, -leɪz/) is a British multinational investment bank and financial services company, headquartered in London, England. Apart from investment banking, Barclays is organised into four core businesses: personal banking, corporate banking, wealth management, and investment management", industry:"Banking") 
Company.create(name:"HSBC", password:"hsbc", address:"Canary Wharf, London", description:"HSBC Holdings plc is a multinational investment bank and financial services holding company. It was the 7th largest bank in the world by 2018, and the largest in Europe, with total assets of US$2.558 trillion (as of December 2018). HSBC traces its origin to a hong in British Hong Kong and its present form was established in London by the Hongkong and Shanghai Banking Corporation to act as a new group holding company in 1991; its name derives from that company's initials.[8] The Hong Kong and Shanghai Banking Corporation opened branches in Shanghai in 1865 and was first formally incorporated in 1866.", industry:"Banking")

Company.create(name:"Mazda", password:"mazda", address:"Fuchu, Hiroshima", description:"Mazda Motor Corporation (Japanese: マツダ株式会社, Hepburn: Matsuda Kabushiki-gaisha) (commonly referred to as simply Mazda) is a Japanese multinational automaker based in Fuchū, Aki District, Hiroshima Prefecture, Japan.[4]", industry:"Car")
Company.create(name:"Mitsubishi", password:"mitsubishi", address:"Shiba, Minato, Japan", description:"Mitsubishi Motors Corporation (Japanese: 三菱自動車工業株式会社, Hepburn: Mitsubishi Jidōsha Kōgyō KK, IPA: [mitsɯꜜbiɕi][6]) is a Japanese multinational automotive manufacturer headquartered in Minato, Tokyo, Japan.[7] In 2011, Mitsubishi Motors was the sixth-largest Japanese automaker and the nineteenth-largest worldwide by production.[8] From October 2016 onwards, Mitsubishi has been one-third (34%) owned by Nissan, and thus a part of the Renault–Nissan–Mitsubishi Alliance.[9]", industry:"Car")